version: '2'

services:
  pdi-srv:
    build: .
    container_name: ${PDI_CONTAINER_NAME}
    command: master
    network_mode: host
    volumes:
      - ./data/logs:/data-integration/logs:rw
      - ./data/cache:/data-integration/system/karaf/caches:rw
      - ./data/data:/data-integration/system/karaf/data:rw
      - ./data/tmp:/tmp:rw
    environment:
      # uncomment below if you want to see the generated admin password
      #DEBUG: Y
      PENTAHO_DI_JAVA_OPTIONS: '${PENTAHO_DI_JAVA_OPTIONS}'
      HOST_USER_ID: ${HOST_USER_ID}
      PDI_MAX_LOG_LINES: ${PDI_MAX_LOG_LINES}
      PDI_MAX_LOG_TIMEOUT: ${PDI_MAX_LOG_TIMEOUT}
      PDI_MAX_OBJ_TIMEOUT: ${PDI_MAX_OBJ_TIMEOUT}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_USER: ${SERVER_USER}
      SERVER_PASSWD: ${SERVER_PASSWD}
      MASTER_NAME: ${MASTER_NAME}
      MASTER_HOST: ${MASTER_HOST}
      MASTER_PORT: ${MASTER_PORT}
      MASTER_CONTEXT: ${MASTER_CONTEXT}
      MASTER_USER: ${MASTER_USER}
      MASTER_PASSWD: ${MASTER_PASSWD}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: always
